import enum


class TOKEN_TYPES(enum.Enum):
    (NUM, STRING, ID, PRINT, READ, ASK, APPROPRIATION,
     IF, ELSE, ENDIF, WHILE, ENDWHILE, PLUS, PLUSONE,
     MINUS, MINUSONE, DIVIDE, MULTIPLY,
     NOTEQ, EQUALS, LESS, MORE, EQLESS, EQMORE,
     PUNCTUATION, RPAR, LPAR, LBRA, RBRA, SEMICOLON,
     QUESTION, EXCLAMATION, DOT, TWOPOINTS,
     STARTCLASS, ENDCLASS, STARTMETHOD, ENDMETHOD, RETURN, CALLMETHOD,
     NAMEMETHOD, MAINMETHOD,
     TYPE) = range(43)

